@baseUrl = http://192.168.43.34:3000

### Update Avatar
PUT {{baseUrl}}/api/avatar/15?token=7FC2D72AB1D9E  HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="user_id";

15
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="akm.jpg"
Content-Type: image/jpg

< ./pexels-maxime-francis-427kb.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Get Avatar By Id
GET {{baseUrl}}/api/avatar/1?token=7FC2D72AB1D9E HTTP/1.1
###
